### ISSUE TITLE
Not working on Android 10

### ISSUE THREAD

**Issue by liamwhite** [Atulin/Chryssibooru#18] opened 2020-12-09 06:04 UTC
Tested on marlin (Pixel XL, factory image, not unlocked/rooted) and sunfish (Pixel 4a, LinageOS 17.1). Attempted both mobile data and Wi-Fi.

Logcat from marlin:
```
12-09 01:01:19.458 27026 27057 I flutter : https://derpibooru.org/api/v1/json/search/images?q=TS%2C+(safe)&page=1&key=&per_page=30
12-09 01:01:19.461 27026 27057 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: SocketException: Failed host lookup: 'derpibooru.org' (OS Error: No address associated with hostname, errno = 7)
12-09 01:01:19.461 27026 27057 E flutter : 
```

Logcat from sunfish:
```
12-09 00:46:35.445  8376  8376 W DartWorker: type=1400 audit(0.0:103): avc: denied { lock } for path="/system/etc/hosts" dev="dm-0" ino=619 scontext=u:r:untrusted_app:s0:c171,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.angius.chryssibooru
12-09 00:46:35.471  8376  8376 W DartWorker: type=1400 audit(0.0:104): avc: denied { lock } for path="/system/etc/hosts" dev="dm-0" ino=619 scontext=u:r:untrusted_app:s0:c171,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.angius.chryssibooru
12-09 00:46:35.498  8376 14822 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: SocketException: Failed host lookup: 'derpibooru.org' (OS Error: No address associated with hostname, errno = 7)
12-09 00:46:35.498  8376 14822 E flutter : 
```

**Comment by Atulin** [comment] 2020-12-09 14:15
Weird, the error implies the issue is with DNS lookup, so something Derpibooru-side, whether it be their server or any proxy they might be using. I don't think it's a Chryssibooru error, but I can fire up an Android 10 emulator and check.

Can you access the logged address ([this link](https://derpibooru.org/api/v1/json/search/images?q=TS%2C+(safe)&page=1&key=&per_page=30)) via a regular browser?

**Comment by liamwhite** [comment] 2020-12-09 16:10
Yes, I can access it via both Chrome and Android WebView.

**Comment by Atulin** [comment] 2020-12-09 16:38
Check if [this build](https://github.com/Atulin/Chryssibooru/releases/tag/v1.6.2) perhaps solves the issue

**Comment by liamwhite** [comment] 2020-12-09 16:40
Indeed it does.

**Comment by Atulin** [comment] 2020-12-09 17:13
Great! That means I need to be more cautious with development, since the issue was with an internet permission not being requested. That, somehow, wasn't an issue in any of test builds, but is an issue in the full release.

Closing as solved.

**Closed as completed by Atulin** 2020-12-09 17:13 UTC
Labels: bug, needs testing
